-- Red Alert Database Schema
-- Version: V1
-- Description: Complete initial schema with categories and alerts

-- =====================================================
-- CATEGORIES TABLE
-- Stores email monitoring category configurations
-- =====================================================
CREATE TABLE IF NOT EXISTS categories (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255),
    from_filter VARCHAR(255),          -- Email sender filter (e.g., fullcycle.com.br)
    subject_keywords VARCHAR(500),     -- Keywords to search in subject (comma separated)
    body_keywords VARCHAR(500),        -- Keywords to search in body (comma separated)
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index for active categories
CREATE INDEX idx_categories_active ON categories(is_active);

-- Comments for documentation
COMMENT ON TABLE categories IS 'Stores email monitoring category configurations';
COMMENT ON COLUMN categories.name IS 'Category name (unique identifier)';
COMMENT ON COLUMN categories.description IS 'Human-readable description';
COMMENT ON COLUMN categories.from_filter IS 'Email sender filter (from:)';
COMMENT ON COLUMN categories.subject_keywords IS 'Keywords to search in subject (comma separated)';
COMMENT ON COLUMN categories.body_keywords IS 'Keywords to search in email body (comma separated)';
COMMENT ON COLUMN categories.is_active IS 'Whether this category is actively monitored';

-- =====================================================
-- ALERTS TABLE
-- Stores all alerts generated by the system
-- =====================================================
CREATE TABLE IF NOT EXISTS alerts (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    alert_date TIMESTAMP NOT NULL,
    url VARCHAR(500),
    is_urgent BOOLEAN NOT NULL DEFAULT false,
    email_id VARCHAR(255),
    email_from VARCHAR(255),
    email_subject VARCHAR(500),
    category_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Foreign key to categories (optional)
    CONSTRAINT fk_alert_category FOREIGN KEY (category_id) 
        REFERENCES categories(id) ON DELETE SET NULL
);

-- Create indexes for better query performance
CREATE INDEX idx_alerts_date ON alerts(alert_date DESC);
CREATE INDEX idx_alerts_urgent ON alerts(is_urgent) WHERE is_urgent = true;
CREATE INDEX idx_alerts_category ON alerts(category_id);
CREATE INDEX idx_alerts_created ON alerts(created_at DESC);

-- Comments for documentation
COMMENT ON TABLE alerts IS 'Stores all alerts generated by the system';
COMMENT ON COLUMN alerts.title IS 'Alert title/summary';
COMMENT ON COLUMN alerts.alert_date IS 'Date/time when the event should occur';
COMMENT ON COLUMN alerts.url IS 'URL link (e.g., Google Meet link)';
COMMENT ON COLUMN alerts.is_urgent IS 'Whether this alert is marked as urgent';
COMMENT ON COLUMN alerts.email_id IS 'Gmail message ID that triggered this alert';
COMMENT ON COLUMN alerts.category_id IS 'Category that triggered this alert (optional)';

-- =====================================================
-- INITIAL DATA
-- Default categories for Quick Start
-- =====================================================
INSERT INTO categories (name, description, from_filter, subject_keywords, body_keywords, is_active) VALUES
('Full Cycle', 'Alertas de aulas ao vivo da Full Cycle', 'fullcycle.com.br', 'AO VIVO, MBA, AGORA', 'link de acesso, aula', true),
('FCTECH', 'Emails importantes da FCTECH', 'fctech.com.br', 'importante, urgente', '', true);
