-- Red Alert Database Schema
-- Version: V2
-- Description: Create alerts table for persistent alert history

-- Create alerts table
CREATE TABLE IF NOT EXISTS alerts (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    alert_date TIMESTAMP NOT NULL,
    url VARCHAR(500),
    is_urgent BOOLEAN NOT NULL DEFAULT false,
    email_id VARCHAR(255),
    email_from VARCHAR(255),
    email_subject VARCHAR(500),
    category_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Foreign key to categories (optional)
    CONSTRAINT fk_alert_category FOREIGN KEY (category_id) 
        REFERENCES categories(id) ON DELETE SET NULL
);

-- Create indexes for better query performance
CREATE INDEX idx_alerts_date ON alerts(alert_date DESC);
CREATE INDEX idx_alerts_urgent ON alerts(is_urgent) WHERE is_urgent = true;
CREATE INDEX idx_alerts_category ON alerts(category_id);
CREATE INDEX idx_alerts_created ON alerts(created_at DESC);

-- Comments for documentation
COMMENT ON TABLE alerts IS 'Stores all alerts generated by the system';
COMMENT ON COLUMN alerts.title IS 'Alert title/summary';
COMMENT ON COLUMN alerts.description IS 'Detailed alert description';
COMMENT ON COLUMN alerts.alert_date IS 'Date/time when the event should occur';
COMMENT ON COLUMN alerts.url IS 'URL link (e.g., Google Meet link)';
COMMENT ON COLUMN alerts.is_urgent IS 'Whether this alert is marked as urgent';
COMMENT ON COLUMN alerts.email_id IS 'Gmail message ID that triggered this alert';
COMMENT ON COLUMN alerts.email_from IS 'Email sender';
COMMENT ON COLUMN alerts.email_subject IS 'Email subject';
COMMENT ON COLUMN alerts.category_id IS 'Category that triggered this alert (optional)';
COMMENT ON COLUMN alerts.created_at IS 'Timestamp when alert was created in the system';
